eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/miammm/spring_cloud
          search-paths: helloworldConfig
          username: 936741678@qq.com
          password: Wang.5738566
  application:
    name: config-server