eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8766

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/miammm/spring_cloud
          searchPaths: spring_cloud/helloworldConfig
  application:
    name: config-server